package entity;

import java.util.Date;

public class UserSample {
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user_sample.ID
	 *
	 * @mbg.generated Sun Nov 29 13:57:47 JST 2020
	 */
	private String id;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user_sample.NAME
	 *
	 * @mbg.generated Sun Nov 29 13:57:47 JST 2020
	 */
	private String name;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user_sample.UPDATE_DATE
	 *
	 * @mbg.generated Sun Nov 29 13:57:47 JST 2020
	 */
	private Date updateDate;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user_sample.ID
	 *
	 * @return the value of user_sample.ID
	 *
	 * @mbg.generated Sun Nov 29 13:57:47 JST 2020
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user_sample.ID
	 *
	 * @param id the value for user_sample.ID
	 *
	 * @mbg.generated Sun Nov 29 13:57:47 JST 2020
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user_sample.NAME
	 *
	 * @return the value of user_sample.NAME
	 *
	 * @mbg.generated Sun Nov 29 13:57:47 JST 2020
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user_sample.NAME
	 *
	 * @param name the value for user_sample.NAME
	 *
	 * @mbg.generated Sun Nov 29 13:57:47 JST 2020
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user_sample.UPDATE_DATE
	 *
	 * @return the value of user_sample.UPDATE_DATE
	 *
	 * @mbg.generated Sun Nov 29 13:57:47 JST 2020
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user_sample.UPDATE_DATE
	 *
	 * @param updateDate the value for user_sample.UPDATE_DATE
	 *
	 * @mbg.generated Sun Nov 29 13:57:47 JST 2020
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 *
	 */
	public UserSample() {
	}

	/**
	 * @param id
	 * @param name
	 * @param updateDate
	 */
	public UserSample(String id, String name, Date updateDate) {
		this.id = id;
		this.name = name;
		this.updateDate = updateDate;
	}
}